name: "Playwright test"

on: push
jobs:
    login-test: 
      runs-on: ubuntu-22.04
      container: 'mcr.microsoft.com/playwright:v1.49.0-noble'
      steps:
        - name: "Login to test repository"
          uses: actions/checkout@v4
          with:
            repository: '${{github.repository}}'
            ref: '${{github.ref}}'
        - name: "install node js"
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: "Install dependencies"
          run: npm ci
        - name: "Run tests"
          run: npm run test
        - name: "Upload report to artifacts"
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: ci-report
            path: playwright-report/
            retention-days: 3 

